services:
  nest:
    - name: backend
      description: Backend service (NestJS)
      database:
        enabled: true
        name: backend_db
        user: backend_user
        passwordSecret: DB_PASSWORD
    - name: core-auth-bff
      description: "core-auth-bff "
      database:
        enabled: true
        name: core_auth_bff_db
        user: core_auth_bff_user
        passwordSecret: DB_PASSWORD
  next:
    - name: frontend
      description: Frontend service (Next.js)
