services:
  nest:
    - name: core-auth-bff
      description: "core-auth-bff "
      database:
        enabled: true
        name: core_auth_bff_db
        user: core_auth_bff_user
        passwordSecret: DB_PASSWORD
    - name: core-recipes-bff
      description: "recipes backend "
      database:
        enabled: true
        name: core_recipes_bff_db
        user: core_recipes_bff_user
        passwordSecret: DB_PASSWORD
  next:
    - name: frontend
      description: Frontend service (Next.js)
