services:
  nest:
    - name: backend
      description: Backend service (NestJS)
      database:
        enabled: true
        name: backend_db
        user: backend_user
        passwordSecret: DB_PASSWORD
    - name: auth-bff
      description: "authorization backend "
      database:
        enabled: true
        name: auth_bff_db
        user: auth_bff_user
        passwordSecret: DB_PASSWORD
  next:
    - name: frontend
      description: Frontend service (Next.js)
