services:
  nest:
    - name: backend
      description: Backend service (NestJS)
      database:
        enabled: true
    - name: core-auth-bff
      description: "core-auth-bff "
      database:
        enabled: true
    - name: core-recipes-bff
      description: "recipes backend "
      database:
        enabled: true
  next:
    - name: frontend
      description: Frontend service (Next.js)
