{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.rules }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.ingress.name }}-{{ .service }}
  namespace: {{ $.Values.ingress.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- if eq .type "nest" }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        {{- if eq $.type "nest" }}
        pathType: ImplementationSpecific
        {{- else }}
        pathType: Prefix
        {{- end }}
        backend:
          service:
            name: {{ $.service }}
            port:
              number: {{ $.port }}
      {{- end }}
{{- end }}
{{- end }}