{{- if .Values.ingress.enabled }}
{{- range $rule := .Values.ingress.rules }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.ingress.name }}-{{ $rule.service }}
  namespace: {{ $.Values.ingress.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  {{- if $.Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- range $.Values.ingress.tls.hosts }}
    - {{ . }}
    {{- end }}
    secretName: {{ $.Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  - http:
      paths:
      {{- range $rule.paths }}
      - path: {{ .path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $rule.service }}
            port:
              number: {{ $rule.port }}
      {{- end }}
{{- end }}
{{- end }}