apiVersion: v2
name: grafana
description: Grafana for metrics visualization
type: application
version: 1.0.1
appVersion: '11.4.0'

dependencies:
  - name: grafana
    version: 8.8.2
    repository: https://grafana.github.io/helm-charts
