name: pre-commit checks
on:
  pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  precommit-service-generation:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - run: pip install pre-commit
      - run: pre-commit --version
      - run: pre-commit install
      - run: pre-commit run --all-files || true
      
      - name: Run format
        run: pnpm format
      
      # Проверяем есть ли изменения. Если есть то совершаем коммит и пуш
      - id: check_changes
        run: |
          git diff --quiet && echo "::set-output name=changes_detected::false" || echo "::set-output name=changes_detected::true"
      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git config --global user.email "246592117+madara-robot@users.noreply.github.com"
          git config --global user.name "madara-robot"
          git add .
          git commit -m "<Madara Robot>: Apply pre-commit hooks fixes" || true
          git push
