name: NodeJS CI push

on:
  push:
    # TODO: возможно стоит удалить фильтр
    # branches: [ $default-branch ]
  pull_request:
    # branches: [ $default-branch ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"
    - name: Setup npm registry
      run: |
        echo "registry=https://registry.npmjs.org/" >> .npmrc
      shell: bash
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
      # env:
      #   NODE_OPTIONS: "--max-old-space-size=4096"
  lint: 
    needs: [install]
    runs-on: ubuntu-latest
    steps:
    - name: lint
      run: pnpm lint
  tsc: 
    needs: [install]
    runs-on: ubuntu-latest
    steps:
    - name: tsc
      run: pnpm -r tsc
  unit: 
    needs: [install]
    runs-on: ubuntu-latest
    steps:
    - name: unit
      run: pnpm -r unit 
  # TODO: add stylelint & etc
