name: security checks for project
on:
  push:
    branches: [main]
  pull_request:
jobs:
  # run security scan for all nest js services
  security-scan-nest:
    name: Security scan for NestJS ${{ matrix.service-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name:
          - backend
          - core-auth-bff
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Security scan check for service ${{ matrix.service-name }}
        uses: ./.github/workflows/jobs/nest-application-security-check
        with:
          service-name: ${{ matrix.service-name }}

  # run security scan for all next js services
  security-scan-next:
    name: Security scan for Next.js ${{ matrix.service-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name:
          - frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Security scan check for service ${{ matrix.service-name }}
        uses: ./.github/workflows/jobs/next-application-security-check
        with:
          service-name: ${{ matrix.service-name }}

  # final job that waits for all security checks
  security-checks-summary:
    name: Security checks summary
    runs-on: ubuntu-latest
    needs: [security-scan-nest, security-scan-next]
    if: always()
    steps:
      - name: Check all security scans status
        run: |
          if [ "${{ needs.security-scan-nest.result }}" != "success" ] || [ "${{ needs.security-scan-next.result }}" != "success" ]; then
            echo "Some security checks failed"
            exit 1
          else
            echo "All security checks passed"
          fi
