name: security checks for project
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  security-scan-backend:
    name: Security scan for services/backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name: ['backend']
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Security scan check for service Backend
        uses: ./.github/workflows/jobs/nest-application-security-check
        with:
          service-name: ${{ matrix.service-name }}

  # run security scan for all next js services
  security-scan-next:
    name: Security scan for Next.js ${{ matrix.service-name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name: ['frontend']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Security scan check for service ${{ matrix.service-name }}
        uses: ./.github/workflows/jobs/next-application-security-check
        with:
          service-name: ${{ matrix.service-name }}
