name: security checks for project
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  security-scan-backend:
    name: Security scan for services/backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name: ['backend'] # Добавьте сюда другие NestJS сервисы
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Security scan check for service Backend
        uses: ./.github/workflows/jobs/nest-application-security-check
        with:
          service-name: ${{ matrix.service-name }}
